#ENV variable
export PATH=".:$HOME/bin/clippy:$HOME/bin/virtme-ng:$HOME/node/bin:$HOME/bin:$HOME/script:$HOME/homebrew/bin:$HOME/.cargo/bin:/usr/local/texlive/2020/bin/x86_64-darwin:$PATH"
#export LC_ALL=en_US.UTF-8
#export LC_CTYPE=UTF-8
export HISTFILE=$HOME/.zsh-history
export HISTSIZE=50000
export SAVEHIST=50000
export EDITOR=vim
export TZ='Asia/Tokyo'
